[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pypdf2>=3.0.1",
    "streamlit-js-eval>=0.1.7",
    "streamlit>=1.42.0",
    "trafilatura>=2.0.0",
    "pillow>=11.1.0",
    "img2pdf>=0.6.0",
    "python-docx>=1.1.2",
    "reportlab>=4.3.1",
    "openai>=1.64.0",
    "pdfminer-six>=20240706",
    "pdf2image>=1.17.0",
    "docx>=0.2.4",
]
